# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CHIBLEE' do
pod  'GoogleMaps', '~> 1.10.4'
pod  'Reachability'
pod  'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Google/SignIn'
pod 'SVProgressHUD'
pod 'Google/Analytics'
pod 'MoEngage-iOS-SDK'
pod 'GKFadeNavigationController'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AppsFlyer-SDK'
pod 'Flurry-iOS-SDK/FlurrySDK', '7.1.0'
pod 'AFNetworking', '~> 3.0'

pod 'CCBottomRefreshControl'
pod 'Toast', '~> 3.0'
pod 'TLYShyNavBar'

end

target 'CHIBLEETests' do

end

target 'CHIBLEEUITests' do

end

